#include "portable_interrupts.h"

//TODO: CREATE VECTOR TABLE USING C SOURCE MODULE AND NOT USING A CUSTOM STARTUP FILE.

//TODO: SEE IF ITS POSSIBLE TO GENERATE STACK INITIALIZATION CODE USING C SOURCE INSTEAD OF PROCESSOR-SPECIFIC ASM

//TODO: SEE IF ITS POSSIBLE TO INIT DATA SEG USING C SOURCE CODE (UNLIKELY) - LINKER PROBABLY HAS TO DO THIS
