
#include "rimot_stm32f411xe_peripherals.h"

/* 
 * This is literally just because I'm lazy 
 * and don't want to type out the 
 * initializer for each peripheral field 
 */
#define __PERIPH_INSTANCE_MAP_INIT(x) x = _ ## x

struct periph_map perip = 
{   
    .__PERIPH_INSTANCE_MAP_INIT(ADC1_COMMON),
    .__PERIPH_INSTANCE_MAP_INIT(ADC1),
    .__PERIPH_INSTANCE_MAP_INIT(DMA1),
    .__PERIPH_INSTANCE_MAP_INIT(DMA2),
    .__PERIPH_INSTANCE_MAP_INIT(CRC),
    .__PERIPH_INSTANCE_MAP_INIT(EXTI),
    .__PERIPH_INSTANCE_MAP_INIT(FLASH),
    .__PERIPH_INSTANCE_MAP_INIT(GPIOA),
    .__PERIPH_INSTANCE_MAP_INIT(GPIOB),
    .__PERIPH_INSTANCE_MAP_INIT(GPIOC),
    .__PERIPH_INSTANCE_MAP_INIT(GPIOD),
    .__PERIPH_INSTANCE_MAP_INIT(GPIOE),
    .__PERIPH_INSTANCE_MAP_INIT(GPIOH),
    .__PERIPH_INSTANCE_MAP_INIT(IWDG),
    .__PERIPH_INSTANCE_MAP_INIT(I2C1),
    .__PERIPH_INSTANCE_MAP_INIT(I2C2),
    .__PERIPH_INSTANCE_MAP_INIT(I2C3),
    .__PERIPH_INSTANCE_MAP_INIT(MCUDBG),
    .__PERIPH_INSTANCE_MAP_INIT(PWR),
    .__PERIPH_INSTANCE_MAP_INIT(RCC),
    .__PERIPH_INSTANCE_MAP_INIT(RTC),
    .__PERIPH_INSTANCE_MAP_INIT(SDIO),
    .__PERIPH_INSTANCE_MAP_INIT(SPI1),
    .__PERIPH_INSTANCE_MAP_INIT(SPI2),
    .__PERIPH_INSTANCE_MAP_INIT(SPI3),
    .__PERIPH_INSTANCE_MAP_INIT(SPI4),
    .__PERIPH_INSTANCE_MAP_INIT(SPI5),
    .__PERIPH_INSTANCE_MAP_INIT(SYSCFG),
    .__PERIPH_INSTANCE_MAP_INIT(TIM1),
    .__PERIPH_INSTANCE_MAP_INIT(TIM2),
    .__PERIPH_INSTANCE_MAP_INIT(TIM3),
    .__PERIPH_INSTANCE_MAP_INIT(TIM4),
    .__PERIPH_INSTANCE_MAP_INIT(TIM5),
    .__PERIPH_INSTANCE_MAP_INIT(TIM9),
    .__PERIPH_INSTANCE_MAP_INIT(TIM10),
    .__PERIPH_INSTANCE_MAP_INIT(TIM11),
    .__PERIPH_INSTANCE_MAP_INIT(USART1),
    .__PERIPH_INSTANCE_MAP_INIT(USART2),
    .__PERIPH_INSTANCE_MAP_INIT(USART6),
    .__PERIPH_INSTANCE_MAP_INIT(USB),
    .__PERIPH_INSTANCE_MAP_INIT(WWDG),
};