/**
 * @file rimot_cortex_interrupts.c
 * @author Carl Mattatall (carl.mattatall@rimot.io)
 * @brief This module provides the definitions for exceptions 
 * generated by the control unit (Cortex M4) on stm32f411 mcu.
 * 
 * @note For declarations of these functions, see the 
 * startup assembly code for the firmware. They are not
 * declared in header files.
 * 
 * @version 0.1
 * @date 2020-04-09
 * 
 * @copyright Copyright (c) 2020 Rimot.io Incorporated
 * 
 */

#include <stdint.h>

#include "rimot_LL_debug.h"

/* DEFINED IN rimot_interrupts.c */
extern uint32_t tickCount;


/**
  * @brief This function handles Non maskable interrupt.
  */
void NMI_Handler(void)
{
    while(1);
}


/**
  * @brief This function handles Hard fault interrupt.
  */
void HardFault_Handler(void)
{

    while (1)
    {
        /* Hang forever */
    }
}


/**
  * @brief This function handles Memory management fault.
  */
void MemManage_Handler(void)
{
    while (1)
    {
        /* Hang forever */
    }
}


/**
  * @brief This function handles Pre-fetch fault, memory access fault.
  */
void BusFault_Handler(void)
{
    while (1)
    {
        /* Hang forever */
    }
}


/**
  * @brief This function handles Undefined instruction or illegal state.
  */
void UsageFault_Handler(void)
{

    while (1)
    {
        /* hang forever */
    }
}


/**
  * @brief This function handles System service call via SWI instruction.
  */
void SVC_Handler(void)
{

}


/**
  * @brief This function handles Debug monitor pause exception.
  * @note for crying out loud if you ever comment this out you can't 
  * actually debug your application. SO DON'T COMMENT IT OUT.
  */
void DebugMon_Handler(void)
{

}


/**
  * @brief This function handles Pendable request for system service.
  */
void PendSV_Handler(void)
{

}

/**
  * @brief This function handles System tick timer.
  */
void SysTick_Handler(void)
{
    tickCount++;
}
