#ifndef __BOOTJUMP_H__
#define __BOOTJUMP_H__
#ifdef __cplusplus
/* clang-format off */
extern "C"
{
/* clang-format on */
#endif /* Start C linkage */

#if defined(STM32F405xx)
#elif defined(STM32F415xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F407xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F417xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F427xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F437xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F429xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F439xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F401xC)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F401xE)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F410Tx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F410Cx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F410Rx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F411xE)

/* Application note AN2606
 * SECTION 8.1, TABLE 15, READ COMMENTS SECTION
 */
#define USBD_DFU_APP_DEFAULT_ADDRESS 0x1FFFC400
#elif defined(STM32F446xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F469xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F479xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F412Cx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F412Zx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F412Rx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F412Vx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F413xx)
#error BOOTLOADER ADDRESS NOT DEFINED FOR THIS DEVICE
#elif defined(STM32F423xx)
#else
#error UNKNOWN TARGET DEVICE IN BOOTJUMP.h
#endif

void SysMemBootJump(void);


#ifdef __cplusplus
/* clang-format off */
}
/* clang-format on */
#endif /* End C linkage */
#endif /* __BOOTJUMP_H__ */
